use_frameworks!

platform :ios, '9.0'

target 'Pandora_Example' do
  pod 'Pandora', :path => '../'

  target 'Pandora_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
